pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "mogueye87/simple-nginx-app"
    }

    stages {
        stage('Build') {
            steps {
                echo 'Hello world'
                sh 'ls -lah'
            }
        }
        stage('Lint HTML') {
            steps {
                sh 'tidy -q -e *.html'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build("mogueye87/simple-nginx-app")
                    app.inside {
                        sh 'echo $(curl localhost:8080)'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_login') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }

		stage('Setting EKS Context') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-eks-login') {
					sh 'kubectl config use-context arn:aws:eks:us-west-2:878823922774:cluster/EKSCloudDevOpsCapstone'
				}
			}
		}

		stage('Deploy to Blue container') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-eks-login') {
					sh 'kubectl apply -f ./nginx-blue-controller.json'
				}
			}
		}

		stage('Deploy Green Container') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-eks-login') {
					sh 'kubectl apply -f ./nginx-green-controller.json'
				}
			}
		}

		stage('Replication Service for Blue Environment') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-eks-login') {
					sh 'kubectl apply -f ./nginx-blue-service.json'
				}
			}
		}

		stage('Replication Service for Green Environment') {
			steps {
                input 'Redirect traffic to green environment?'
				withAWS(region:'us-west-2', credentials:'aws-eks-login') {
				sh 'kubectl apply -f ./nginx-green-service.json'
				}
			}
		}
   }
}